#!/usr/bin/perl -w

use strict;
use Data::Dumper;

my %sections;
my $link = {};
my $count = 0;

my $filename = $ARGV[0];

open IN, $filename or die "Couldn't open file $filename\n";

while (my $line = <IN>) {
    # if we have a blank line reset everything
    if ($line =~ /^$/) {
        push @{$sections{$link->{section}}}, $link if exists $link->{section};
        $link = {};
        $count = 0;
    } else {
        chomp($line);
        if ($count == 0) { # first line is the title
            $link->{title} = $line;
            $count++;
        } elsif ($count == 1) { # second line is the source
            $link->{source} = $line;
            $count++;
        } elsif ($count == 2) { # XXX: third line is the URL
            $link->{url} = $line;
            $count++;
        } elsif ($count == 3) { # XXX: fourth line is the sort key
            $link->{section} = $line;
            $count++;
        }
    }

}

#print Dumper(\%sections);


foreach my $section (keys(%sections)) {
    print "\n\n\n\n$section\n\n";
    my $first = 1;
    foreach my $block (@{$sections{$section}}) {
        print "<br><br>\n" unless $first;
        $first = 0;
        print $block->{title} . ' - <a  alias="' . $block->{source} . '" conversion="false" data-linkto="https://" href="' 
            . $block->{url} . '" style="color:#00B1E7;text-decoration:underline;" title="' 
            . $block->{source} . '">' . $block->{source} . "</a>" . "\n";
   }
}


